### ISSUE TITLE
Create websockets

### ISSUE THREAD

**Issue by dimensi0n** [open-incubator/pymatrix#5]
Move all the print statements to websockets statement. 

Exemple:
```python
print(someone.x, someone.y, ID, ':W')
```
Into
```python
socket.emit('goToWork', {someone.x, someone.y, ID})
```

Using the module of your choice.
This will give us the ability of creating a console in order to manipulate the matrix while it is running.

**Comment by The-Shwin** [comment]
Could I take a shot at this?

**Comment by dimensi0n** [comment]
Of course :wink: if you have any questions do not hesitate to ask here !

**Comment by The-Shwin** [comment]
Created a PR to solve this issue, I think it addresses everything, but feel free to let me know if there was anything to discuss @dimensi0n
